#!/bin/bash

EMAIL=$1
DOMAINS=$(echo -n $2 | sed 's/,/ -d /')
DOCKER_ID=$(hostname)

echo "DOCKER_NAME=\$(docker ps -a --filter 'id=${DOCKER_ID}' --format '{{.Names}}')"
echo "certbot certonly \\"
echo "    --manual \\"
echo "    --manual-auth-hook \"docker exec -e CERTBOT_VALIDATION=\\\${CERTBOT_VALIDATION} -e CERTBOT_DOMAIN=\\\${CERTBOT_DOMAIN}\" \${DOCKER_NAME} auth_hook\""
echo "    --preferred-challenges=dns \\"
echo "    -d $DOMAINS \\"
echo "    --email $EMAIL \\"
echo "    --agree-tos"
